[project]
name = "random-explorer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Pacifique000", email = "ngantaangepacifique@gmail.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
valid-input = "random_explorer.valid_input:main"

[build-system]
requires = ["uv_build>=0.9.26,<0.10.0"]
build-backend = "uv_build"
